config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :customer_intials
  resources :users

  resources :items
  resources :enrollments

  get 'cart_csv' => 'enrollments#cart_csv', as: :cart_csv

  get 'user/:id/empty_cart' => 'enrollments#empty_cart'
  get 'user/:id/remove_a_item' => 'enrollments#remove_a_item', as: :remove
  get 'user/:id/remove_a_item10' => 'enrollments#remove_a_item10', as: :remove10
  
get 'users/:id/add_to_list10' => 'enrollments#create10', as: :add_to_list10
get 'users/:id/add_to_list' => 'enrollments#create', as: :add_to_list

  get 'home/index'
  get 'home' => 'home#index'
  get 'home/xoa' => 'home#xoa_het'
  get 'user/:id/send_order' => 'users#send_price'
  
  root 'items#index'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer_intial.rb
class CustomerIntial < ApplicationRecord
	def self.to_csv
		attributes = %w{ISP_name name spouse_single address county zip email phone alt_phone appoitment_date time best_time_to_confirm home_owners two_hours spouse notes  date store_number}

		CSV.generate(headers: true) do |csv|
			csv << attributes

			all.each do |customer|
				csv << attributes.map{ |attr| customer.send(attr) }
			end
		end
	end
end

app/controllers/customer_intials_controller.rb
class CustomerIntialsController < ApplicationController
  before_action :set_customer_intial, only: [:show, :edit, :update, :destroy]

  # GET /customer_intials
  # GET /customer_intials.json
  def index
    @customer_intials = CustomerIntial.all

      respond_to do |format|
      format.html 
      format.csv { send_data @customer_intials.to_csv }     
      format.xlsx {response.headers['Content-Disposition'] = 'attachment; filename="all_customer.xlsx"'}
    end
  end



  # GET /customer_intials/1
  # GET /customer_intials/1.json
  def show
  end

  # GET /customer_intials/new
  def new
    @customer_intial = CustomerIntial.new
  end

  # GET /customer_intials/1/edit
  def edit
  end

  # POST /customer_intials
  # POST /customer_intials.json
  def create
    @customer_intial = CustomerIntial.new(customer_intial_params)

    
      if @customer_intial.save
    UserMailer.customer_email(@customer_intial).deliver_later  
      flash[:success] = "Welcome to The Home Depot!"
      redirect_to @customer_intial
      else
        format.html { render :new }
        format.json { render json: @customer_intial.errors, status: :unprocessable_entity }
      end
    
  end

  # PATCH/PUT /customer_intials/1
  # PATCH/PUT /customer_intials/1.json
  def update
    respond_to do |format|
      if @customer_intial.update(customer_intial_params)
        flash[:success] = "Customer intial was successfully updated."
        format.html { redirect_to @customer_intial }
        format.json { render :show, status: :ok, location: @customer_intial }
      else
        format.html { render :edit }
        format.json { render json: @customer_intial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_intials/1
  # DELETE /customer_intials/1.json
  def destroy
    @customer_intial.destroy
    respond_to do |format|
      format.html { redirect_to customer_intials_url, notice: 'Customer intial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_intial
      @customer_intial = CustomerIntial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_intial_params
      params.require(:customer_intial).permit(:name, :spouse_single, :address, :county, :zip, :email, :phone, :alt_phone, :appoitment_date, :time, :best_time_to_confirm, :home_owners, :two_hours, :spouse, :notes, :ISP_name, :date, :store_number)
    end
end

app/helpers/customer_intials_helper.rb
module CustomerIntialsHelper
end

app/views/customer_intials/_form.html.erb
<%= form_for(customer_intial,html: {multipart: true, class: ""}) do |f| %>
  <% if customer_intial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_intial.errors.count, "error") %> prohibited this customer_intial from being saved:</h2>

      <ul>
      <% customer_intial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 

    <div class="form-group">
      <%= f.label :ISP_name %>
      <%= f.text_field :ISP_name, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :date %>
      <%= f.text_field :date, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :store_number %>
      <%= f.text_field :store_number, class:"form-control" %>
    </div>



    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
  
    <div class="form-group">
      <%= f.label :spouse_single %>
      <%= f.text_field :spouse_single, class:"form-control" %>
    </div>
  
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_area :address, class:"form-control" %>
  </div>
  
    <div class="form-group">
      <%= f.label :county %>
      <%= f.text_field :county, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :zip %>
      <%= f.number_field :zip, class:"form-control" %>
    </div>
  

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control" %>
  </div>

  
      <div class="form-group">
        <%= f.label :phone %>
        <%= f.number_field :phone, class:"form-control", type:"tel", value: "1-(555)-555-5555" %>
      </div>

      <div class="form-group">
        <%= f.label :alt_phone %>
        <%= f.number_field :alt_phone, class:"form-control" %>
      </div>
   

 
      <div class="form-group">
        <%= f.label :appoitment_date %>
        <%= f.date_select :appoitment_date, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :time %>
        <%= f.time_select :time, class:"form-control" %>
      </div>
  

      <div class="form-group">
        <%= f.label :best_time_to_confirm %>
        <%= f.time_select :best_time_to_confirm, class:"form-control" %>
      </div>
   
  

    <div class="form-check">
      <label class="form-check-label"> 
        <%= f.check_box :home_owners, class: "form-check-input", type:"checkbox" %>
        <%= f.label :home_owners %>
      </label>
    </div>
   
    <div class="form-check">
      <label class="form-check-label"> 
        <%= f.check_box :two_hours, class: "form-check-input", type:"checkbox" %>
        <%= f.label :two_hours %>
      </label>
    </div>

    <div class="form-check">
      <label class="form-check-label"> 
        <%= f.check_box :spouse, class: "form-check-input", type:"checkbox" %>
        <%= f.label :spouse %>
      </label>
    </div>
 

  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: "form-control" %>
  </div>

 

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>


<% end %>

app/views/customer_intials/edit.html.erb
<h1>Editing Customer Intial</h1>

<%= render 'form', customer_intial: @customer_intial %>

<%= link_to 'Show', @customer_intial %> |
<%= link_to 'Back', customer_intials_path %>

app/views/customer_intials/index.html.erb
<div class="row">
<p id="notice"><%= notice %></p>

<h1>Customer Intials</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ISP</th>
      <th>Name</th>
      <th>Spouse single</th>
      <th>Address</th>
      <th>County</th>
      <th>Zip</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Alt phone</th>
      <th>Appoitment date</th>
      <th>Time</th>
      <th>Best time to confirm</th>
      <th>Home owners</th>
      <th>Two hours</th>
      <th>Spouse</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_intials.each do |customer_intial| %>
      <tr>
        <td><%= customer_intial.ISP_name %></td>
        <td><%= customer_intial.name %></td>
        <td><%= customer_intial.spouse_single %></td>
        <td><%= customer_intial.address %></td>
        <td><%= customer_intial.county %></td>
        <td><%= customer_intial.zip %></td>
        <td><%= customer_intial.email %></td>
        <td><%= customer_intial.phone %></td>
        <td><%= customer_intial.alt_phone %></td>
        <td><%= customer_intial.appoitment_date %></td>
        <td><%= customer_intial.time.strftime('%H : %M') %></td>
        <td><%= customer_intial.best_time_to_confirm.strftime('%H : %M') %></td>
        <td><%= customer_intial.home_owners? ? 'Yes' : 'No' %></td>
        <td><%= customer_intial.two_hours? ? 'Yes' : 'No' %></td>
        <td><%= customer_intial.spouse? ? 'Yes' : 'No' %></td>
        <td><%= customer_intial.notes %></td>
        <td><%= link_to 'Show', customer_intial %></td>
        <td><%= link_to 'Edit', edit_customer_intial_path(customer_intial) %></td>
        <td><%= link_to 'Destroy', customer_intial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer Intial', new_customer_intial_path %>
</div>

app/views/customer_intials/new.html.erb
<h1>New Customer Intial</h1>

<%= render 'form', customer_intial: @customer_intial %>

<%= link_to 'Back to store', items_path, class: 'btn btn-secondary' %>

app/views/customer_intials/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>ISP:</strong>
  <%= @customer_intial.ISP_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @customer_intial.date %>
</p>

<p>
  <strong>Store number:</strong>
  <%= @customer_intial.store_number %>
</p>


<p>
  <strong>Name:</strong>
  <%= @customer_intial.name %>
</p>

<p>
  <strong>Spouse single:</strong>
  <%= @customer_intial.spouse_single %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer_intial.address %>
</p>

<p>
  <strong>County:</strong>
  <%= @customer_intial.county %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @customer_intial.zip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer_intial.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer_intial.phone %>
</p>

<p>
  <strong>Alt phone:</strong>
  <%= @customer_intial.alt_phone %>
</p>

<p>
  <strong>Appoitment date:</strong>
  <%= @customer_intial.appoitment_date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @customer_intial.time.strftime('%H : %M') %>
</p>

<p>
  <strong>Best time to confirm:</strong>
  <%= @customer_intial.best_time_to_confirm.strftime('%H : %M') %>
</p>

<p>
  <strong>Home owners:</strong>
  <%= @customer_intial.home_owners? ? 'Yes' : 'No' %>
</p>

<p>
  <strong>Two hours:</strong>
  <%= @customer_intial.two_hours? ? 'Yes' : 'No' %>
</p>

<p>
  <strong>Spouse:</strong>
  <%= @customer_intial.spouse? ? 'Yes' : 'No'  %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @customer_intial.notes %>
</p>

<%= link_to 'Edit', edit_customer_intial_path(@customer_intial), class: 'btn btn-secondary' %> 
<%= link_to 'Add more customer', new_customer_intial_path, class: 'btn btn-secondary' %>