config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :customer_intials
  resources :users

  resources :items
  resources :enrollments

  get 'cart_csv' => 'enrollments#cart_csv', as: :cart_csv

  get 'user/:id/empty_cart' => 'enrollments#empty_cart'
  get 'user/:id/remove_a_item' => 'enrollments#remove_a_item', as: :remove
  get 'user/:id/remove_a_item10' => 'enrollments#remove_a_item10', as: :remove10
  
get 'users/:id/add_to_list10' => 'enrollments#create10', as: :add_to_list10
get 'users/:id/add_to_list' => 'enrollments#create', as: :add_to_list

  get 'home/index'
  get 'home' => 'home#index'
  get 'home/xoa' => 'home#xoa_het'
  get 'user/:id/send_order' => 'users#send_price'
  
  root 'items#index'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :items, through: :enrollments
	has_many :enrollments

	before_save {self.email = email.downcase}
	validates :name, presence: true, 
	 length: {minimum:3, maximum: 25}
	 
	 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	 validates :email, presence: true, length: {maximum: 50},
	 format: {with: VALID_EMAIL_REGEX}

	def add_to_list(item)
		current_item = enrollments.find_by(item_id: item.id)
		if current_item
			current_item.quantity += 1
		else
			current_item = enrollments.build(item_id: item.id)
		end
		current_item
	end

	def remove_from_list(item)
		current_item = enrollments.find_by(item_id: item.id)
		if current_item && current_item.quantity > 1
		current_item.quantity -= 1
		else
			current_item.destroy
		end
		current_item
		
	end

	def remove_from_list10(item)
		current_item = enrollments.find_by(item_id: item.id)
		if current_item && current_item.quantity > 1
		current_item.quantity -= 10
		else
			current_item.destroy
		end
		current_item
		
	end

	def add_to_list10(item)
		current_item = enrollments.find_by(item_id: item.id)
		if current_item
			current_item.quantity += 10
		else
			current_item = enrollments.build(item_id: item.id)
		end
		current_item
	end

	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @items = Item.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

      #mac dinh k co j
    
    @items = Item.all
    @user = User.find(params[:id])

    
  end

  # GET /users/new
  def new
    @user = User.new
   
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @items = Item.all
    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver_later
        
        flash[:success] = "Welcome to Home Depot Home Services"
        format.html { redirect_to(@user) }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = "User was successfully updated."
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_price
    @user = User.find(params[:id])
    flash[:success] = "List Price was sending to your email"
    UserMailer.send_price_email(@user).deliver_later

    respond_to do |format|
          format.js { }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :name, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
    <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :email, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
    <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
 

  

  <div class="form-group row">
     <div class="offset-sm-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', items_path %>

app/views/users/send_price.js.erb
alert('List Price was sending to your email');
//$('#sent-email').append('List Price was sending to your email');

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<body data-turbolinks="false">
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<p>
<%= link_to 'Edit user', edit_user_path(@user) %> |
<%= link_to 'Back', items_path %>

</p>
 


  
 <h2> Your cart </h2>
 <p>Download as: <%=  link_to 'CSV', cart_csv_path(format: :csv)  %> 
<%=  link_to 'XLSX', cart_csv_path(format: :xlsx)  %>
 </p>
 
 <%= link_to 'Add more', items_path, class: "btn btn-success" %>

<%= link_to 'Empty cart', {controller: 'enrollments', action: 'empty_cart'}, class: 'btn btn-warning', data: { confirm: 'Are you sure?' }   %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Line item</th>
      <th>Item</th>
    
      <th>Description</th>
      
     
      <th>Price</th>
      <th>Qty</th>
      <th> Change Qty</th>
      <th><div style="text-align: right">Total</div></th>
      
      
      <th colspan="3"></th>
    </tr>
  </thead>
<% i = 0 %>

  <tbody>
    <%    @user.enrollments.each do |u|    %>
      <tr>
        <td><%= u.item.line_item %></td>
        <td><%= u.item.item %></td>
        <td><%= u.item.description %></td>
        <td><%= u.item.Price %></td>        
        
        <td>&times; <%=  u.quantity %></td>
        <td> 

        <%= link_to add_to_list_path(item_id: u.item), class: 'btn btn-success btn-sm' do %>
        <i class="fa fa-chevron-up" aria-hidden="true"></i>
        <% end %>

        <%= link_to add_to_list10_path(item_id: u.item), class: 'btn btn-success btn-sm' do %>
        <i class="fa fa-chevron-up" aria-hidden="true"> 10</i>
        <% end %></br>

        





        <%= link_to remove_path(item_id: u.item), class: 'btn btn-warning btn-sm' do %>
        <i class="fa fa-chevron-down" aria-hidden="true"></i>
        <% end %>

        <%= link_to remove10_path(item_id: u.item), class: 'btn btn-warning btn-sm' do %>
        <i class="fa fa-chevron-down" aria-hidden="true"> 10</i>
        <% end %>

        </td>
       <td><div style="text-align: right"> <%= u.item.Price.to_i * u.quantity %></div></td>

        <td><%= link_to 'Delete', u, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <td><%= link_to 'Edit', edit_enrollment_path(u) %></td>
      </tr>

      
<% i = u.item.Price.to_i * u.quantity + i %>

    <% end %>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td> <div class="total-line" style="border-top: 1px solid #595; text-align: right">$ <%= i %> </h4></td>
      </tr>
  </tbody>
</table>

  <h4> List Price  <%= i +700 %> 
<%= link_to 'Send me order', {controller: 'users', action: 'send_price'}, remote: true, class: 'btn btn-danger'  %>
 </h4>
 <div id="sent-email"></div>
  <p> 4% of List Price = <%= 4 * (i+700)/100 %> </p>


 <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#discount" aria-expanded="false" aria-controls="collapseExample">
              Show Discount
            </button>
         

          <div class="collapse" id="discount">
              <div class="card card-block">
                <h4>  Admin Fee = <%= 700 %> </h4>
                  <h4>Discount of grand total = <%= n= 9*(i+700)/10 %> </h4>
                 <p> 2% of discount  = <%= 2*9*(i+700)/10/100 %> </p>
                    <h4> Discount of discount = <%= k= n*9/10 %> </h4>
                <p>2% of discount of discount = <%= k*2/100 %> </p>
                <br>
              </div>
          </div>
        </div>
 </div>