config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :customer_intials
  resources :users

  resources :items
  resources :enrollments

  get 'cart_csv' => 'enrollments#cart_csv', as: :cart_csv

  get 'user/:id/empty_cart' => 'enrollments#empty_cart'
  get 'user/:id/remove_a_item' => 'enrollments#remove_a_item', as: :remove
  get 'user/:id/remove_a_item10' => 'enrollments#remove_a_item10', as: :remove10
  
get 'users/:id/add_to_list10' => 'enrollments#create10', as: :add_to_list10
get 'users/:id/add_to_list' => 'enrollments#create', as: :add_to_list

  get 'home/index'
  get 'home' => 'home#index'
  get 'home/xoa' => 'home#xoa_het'
  get 'user/:id/send_order' => 'users#send_price'
  
  root 'items#index'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

mount_uploader :image, ImageUploader

has_many :users, through: :enrollments
has_many :enrollments


	def self.search(search)	
		if search
		    #where('sizes LIKE ?', "%#{search}%")
		    where("sizes ILIKE ? OR LOWER(item) ILIKE ? OR description ILIKE ? OR category ILIKE ? OR line_item::text ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
		else
		  scoped
		end
	end


	def self.to_csv
		attributes = %w{line_item item description sizes factor Price Qty category}

		CSV.generate(headers: true) do |csv|
			csv << attributes

			all.each do |item|
				csv << attributes.map{ |attr| item.send(attr) }
			end
		end
	end

	

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :edit, :update, :destroy]
  #before_action :correct_item,   only: [:edit, :update]
  # GET /items
  # GET /items.json
  def index
    @user = User.new  
    

    @items = Item.all
    if params[:search]
      @items = Item.search(params[:search]).order("line_item ASC")
    else
      @items = Item.order('line_item ASC')
    end 

    respond_to do |format|
      format.html 
      format.json 
      format.js {render layout: false}
      format.csv { send_data @items.to_csv }
      format.xlsx {response.headers['Content-Disposition'] = 'attachment; filename="all_items.xlsx"'}
    end
    
  end

    

  # GET /items/1
  # GET /items/1.json
  def show
    respond_to do |format|
      format.html
      format.js {render layout: false}
    end
  end

  # GET /items/new
  def new
    @item = current_user.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)

    respond_to do |format|     
      if @item.save    

        flash[:success] = "Item was successfully created"
        format.html { redirect_to @item }
        format.json { render :show, status: :created, location: @item }
        format.js {render layout: false}
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        flash[:success] = "Item was successfully updated"
        format.html { redirect_to @item }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:line_item, :item, :description, :sizes, :factor, :Price, :Qty, :category, :image, :remove_image)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

   #def correct_item
   #  @item = Item.find(params[:id])
   #  redirect_to(root_url) unless @item.user == current_user
   #end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item, html: {multipart: true, class: "container"}) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :line_item, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
    <%= f.number_field :line_item, class: "form-control" %>
    </div>
  </div>

 
  <div class="form-group row">
    <%= f.label :item, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
    <%= f.text_field :item, class: "form-control" %>
    </div>
  </div>
<div class="form-group row">
    <%= f.label :description, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
    <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :sizes, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
    <%= f.text_field :sizes, class: "form-control" %>
    </div>
  </div>
 <div class="form-group row">
    <%= f.label :factor, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
    <%= f.text_field :factor, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :Price, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
    <%= f.text_field :Price, class: "form-control" %>
    </div>
  </div>
 

  <div class="form-group row">
    <%= f.label :Qty, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
    <%= f.number_field :Qty, class: "form-control" %>
    </div>
  </div>
<div class="form-group row">
    <%= f.label :category, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
    <%= f.text_field :category, class: "form-control" %>
    </div>
  </div>

 <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
    
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %> 
    <% end %>
    
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>



<%= link_to 'Show', @item, class: "btn btn-outline-success" %> 
<%= link_to 'Back', items_path, class: "btn btn-outline-info" %> 
<%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-warning" %>
<%= render 'form', item: @item %>

app/views/items/index.html.erb
  <div style="padding-bottom: 20px;"></div>
  <nav class="navbar navbar-fixed-top navbar-light bg-faded" style="background-color: #e3f2fd;">


    <%= form_tag(items_path, method: "get", class: "form-inline float-lg-left") do %> 
      <%= text_field_tag :search, params[:search], placeholder: "Search Items", class: "form-control" %>

      <%= submit_tag "Search", :name => nil, class: "btn btn-secondary" %>
      <% end %>
    <%= link_to 'Create Item', new_item_path, class: "btn btn-success" %>
     <%= link_to 'Reset', '#', class: "btn btn-warning", remote: true %>


     <% if logged_in? %>       
          <div class="btn-group">
          <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= @current_user.name %>
          </button>
            <div class="dropdown-menu">
              <%= link_to "My Cart", current_user, class: "dropdown-item" %>
              <a class="dropdown-item" href="#"> About</a>
              <div class="dropdown-divider"></div>
                <%= link_to "Log out", logout_path, method: "delete", class: "dropdown-item" %>
              </div>
        <% else %>
         <%= link_to "Log in", login_path, class: "btn btn-outline-info" %>
        <% end %>
    
  
  </nav>


  <h2> List of Items</h2>
Download as
<%= link_to 'xlsx |', items_path(format: :xlsx) %>
<%= link_to ' CSV', items_path(format: :csv) %>
  <div class="row">



   

   
      <% @items.each do |item| %>
      
        <div class="col-sm-3">
          
              <div class="card">
                 <%= image_tag("#{item.image}", class: "card-img-top img-fluid" ) %>
                  <div class="card-header">
                    <h4 class="card-title"><%= item.line_item %></h4>
                  </div>
                <div class="card-block">

                  
                  <p class="card-text"><%= item.item %></p>
                  <p class="card-text"><%= item.description %></p>
                  
                  <%= link_to 'Show', item, class: "btn btn-primary"  %>

                  <%= button_to enrollments_path(item_id: item), class: 'btn btn-danger' do %>
                  <span class="fa fa-star" aria-hidden="true">Add to list</span>
                  <% end %>

                  <%= link_to 'Edit', edit_item_path(item) %>

                </div>
              </div>
          
      </div>  
      <% end %>
    


 <% i = 0 %>
      <% @items.each do |item| %>
      <% i = item.Price.to_i * item.Qty.to_i + i %>
      <% end %>

<p>
 <h4> List Price  <%= i +700 %> </h4> </p>
             <p> 4% of List Price = <%= 4 * (i+700)/100 %> </p>



 <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#discount" aria-expanded="false" aria-controls="collapseExample">
              Show Discount
            </button>
         

          <div class="collapse" id="discount">
              <div class="card card-block">
                <h4>  Admin Fee = <%= 700 %> </h4>
                  <h4>Discount of grand total = <%= n= 9*(i+700)/10 %> </h4>
                 <p> 2% of discount  = <%= 2*9*(i+700)/10/100 %> </p>
                    <h4> Discount of discount = <%= k= n*9/10 %> </h4>
                <p>2% of discount of discount = <%= k*2/100 %> </p>
                <br>
              </div>
          </div>
        </div>
 </div>

      </div>

  

app/views/items/index.js.erb
alert('reload page to take effect');

<% @items.each do |i| %>
<% i.Qty = 0 %>
<% i.save %>
<% end %>

app/views/items/new.html.erb
<div class="">
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path, class: 'btn btn-secondary' %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'New customer', new_customer_intial_path, class: 'btn btn-primary' %>


        <%= button_to enrollments_path(item_id: @item), class: 'btn btn-danger' do %>
        <span class="fa fa-star" aria-hidden="true">Add to list</span>
        <% end %>

<p>

  <strong>Line item:</strong>
  <%= @item.line_item %>
</p>

<p>
  <strong>Item:</strong>
  <%= @item.item %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Sizes:</strong>
  <%= @item.sizes %>
</p>

<p>
  <strong>Factor:</strong>
  <%= @item.factor %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.Price %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @item.Qty %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<%= image_tag("#{@item.image}", class:"img-fluid") %>


<%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-primary' %>
<%= link_to 'Back', items_path, class: 'btn btn-primary' %>